### ISSUE TITLE
[BUG] OCP3 not available as a product when option2 is chosen for the interactive installation also option errors out

### ISSUE THREAD

**Issue by joecharles33** [flyemsafe/qubinode-installer#37]
**Describe the bug**

**Screenshots**
![image](https://user-images.githubusercontent.com/47707671/71632295-c3bd0b80-2bdb-11ea-9d8d-12fc694a023a.png)

**Additional context**

**Comment by flyemsafe** [comment]
Functionality not implemented yet.
