### ISSUE TITLE
./qubinode-installer -m deploy_nodes -p ocp

### ISSUE THREAD

**Issue by amalivert** [flyemsafe/qubinode-installer#5]
TASK [ansible-role-rhel7-kvm-cloud-init : get vm gateway from DHCP server] ********************
Saturday 09 November 2019  20:28:29 -0500 (0:00:00.253)       0:00:25.871 ***** 
fatal: [localhost]: UNREACHABLE! => {
    "changed": false, 
    "unreachable": true
}

MSG:

Failed to connect to the host via ssh: Warning: Permanently added '192.168.1.45' (ECDSA) to the list of known hosts.
Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).

**Comment by flyemsafe** [comment]
This is not a valid command.

```
./qubinode-installer -m deploy_nodes -p ocp
```

You should just run
```
./qubinode-installer -m deploy_nodes
```
